/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sd.design.patterns;

public class App {
    public String getGreeting() {
        return "Design patterns in action :) !";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
